services:
  postgres:
    image: postgres:16-alpine
    container_name: mcne-postgres
    environment:
      POSTGRES_USER: mcne_user
      POSTGRES_PASSWORD: mcne_password
      POSTGRES_DB: mcne_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: mcne-rabbitmq
    ports:
      - "5672:5672" # Default AMQP communication port
      - "15672:15672" # Management UI port

volumes:
  postgres_data: