spring.application.name=mcne
spring.threads.virtual.enabled=true

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5435/mcne_db
spring.datasource.username=mcne_user
spring.datasource.password=mcne_password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Web Server Config
server.port=8081

# RabbitMQ Logs (Hides the huge stack trace when sending to DLQ)
#logging.level.org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler=ERROR

# AWS Configuration
aws.region=${AWS_REGION:us-east-2}
aws.accessKeyId=${AWS_ACCESS_KEY:none}
aws.secretKey=${AWS_SECRET_KEY:none}
aws.ses.verified-email=${AWS_VERIFIED_EMAIL:none@example.com}
